export const languages = [
        { iso: "en", name: "English" },
        { iso: "es", name: "Spanish" }, 
        { iso: "fr", name: "French" }, 
        { iso: "de", name: "German" }, 
        { iso: "it", name: "Italian" }, 
        { iso: "ru", name: "Russian" }, 
        { iso: "pt", name: "Portuguese" }, 
        { iso: "zh", name: "Chinese" }, 
        { iso: "ja", name: "Japanese" }, 
        { iso: "hi", name: "Hindi" }, 
        { iso: "ar", name: "Arabic" }, 
        { iso: "ko", name: "Korean" }, 
        { iso: "pl", name: "Polish" }, 
        { iso: "tr", name: "Turkish" }, 
        { iso: "vi", name: "Vietnamese" }, 
        { iso: "id", name: "Indonesian" }, 
        { iso: "nl", name: "Dutch" }, 
        { iso: "fa", name: "Farsi" }, 
        { iso: "th", name: "Thai" }, 
        { iso: "af", name: "Afrikaans" } 
    ]